### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by ghost91-** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#1]
Hi @Cyr- and @MikauSchekzen,

I have adopted this module from @schultzcole. I would like to change the license from GPL to MIT, to which he has already agreed. However, as you also contributed parts of the code, I also need your permission to re-license to MIT. Would you be OK with that?

**Comment by MikauSchekzen** [comment]
Aye, sounds good to me.
