### ISSUE TITLE
PF2e?

### ISSUE THREAD

**Issue by belkasro** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#154]
Will there be Pathfinder 2e support in the future?

**Comment by ghost91-** [comment]
Only if somebody cares to add support for it. I personally won’t do it since I don’t ply pf2e. But I’m happy to accept PRs.

**Comment by ghost91-** [comment]
Closing this as wontfix, since I don't have the capabilities to do it myself, and apparently nobody else wants to do it.
