### ISSUE TITLE
Hitting the @ starts the prompt, but doesn't add the @ to the property

### ISSUE THREAD

**Issue by GambetTV** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#157]
This is very strange, as this has only popped up in the last week or two, and you haven't updated the module in a month so I genuinely don't know what has happened, but essentially when I type in a damage field say, 1d10 + @mod, when I hit the @ symbol the prompt comes up giving me the list of all the possible things I might attach, like traits or classes or mod or whatever. If I then type out mod and hit enter, it doesn't add the @ symbol anymore.

So I might type 1d10 + @mod, but what comes out is 1d10 + mod. Foundry doesn't register this, and the dice don't roll. Very strange!

**Comment by ghost91-** [comment]
Thanks for the report, I’ll take a look as soon as possible.
