### ISSUE TITLE
Autocompleting a property returns to the start of the line

### ISSUE THREAD

**Issue by louisch** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#189]
Using v10 at the moment, and on an autocomplete the cursor moves back to the start of the line. If this is intentional, would it be possible to get a setting to turn this off? I would like to be able to continue editing the line after autocompleting something.

**Comment by ghost91-** [comment]
Thanks for the report, that’s not intended. I’ll try to take a look, but it might take a while, since I’ll be on vacation for a week, starting tomorrow.
