### ISSUE TITLE
Inline options windows don't populate when typing.

### ISSUE THREAD

**Issue by AGMacD** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#192]
Inline options windows don't populate when typing.

Using Foundry 9.280
Latest version of Auto Inline 2.8.1
System PF1 version 0.81.3

![1](https://user-images.githubusercontent.com/112817267/188321622-d48b9490-fed0-4e8b-96f6-4410281fcda6.PNG)
![2](https://user-images.githubusercontent.com/112817267/188321624-d106a301-4261-4c3a-811d-c442b85bfed1.PNG)

**Comment by ghost91-** [comment]
Currently on vacation, I’ll take a look when I’m back (next week).

**Comment by AGMacD** [comment]
Update to my previous post, It seems like it isn't working in the new "Sub tabs" in attacks / actions for weapons & Spells. It does still seem to work everywhere else I can think of checking. Hope this helps 

![3](https://user-images.githubusercontent.com/112817267/189489065-00785f44-0249-454c-83a0-e363ca547d46.PNG)
![4](https://user-images.githubusercontent.com/112817267/189489066-47a05009-abb9-4682-8e42-1850c9d22a80.PNG)
![5](https://user-images.githubusercontent.com/112817267/189489194-383cf23a-beb7-46fb-9e72-cf039af0948e.PNG)
![6](https://user-images.githubusercontent.com/112817267/189489298-f6ed5ee7-805f-45f0-8a58-a88ff8164557.PNG)
