### ISSUE TITLE
Not sure what's going on

### ISSUE THREAD

**Issue by Nedrapter** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#32]
I noticed that the module is doing nothing today. I'm using dnd5e, in the app, in opera and in firefox .
I remember typing "@sk" and it would show me the table with all the @skills. options for example. Now nothing shows up, no table, nothing, as if the module is deactivated.
I deactivated every other module. I used Find the Culprit. I re-activated it.
I'm at a dead end :(

**Comment by ghost91-** [comment]
Hey @Nedrapter, sorry, I kind of missed this. Does the problem still appear?

**Comment by Nedrapter** [comment]
I uninstalled it and reinstalled it and fixed the issue, took me a while to think of that...
