### ISSUE TITLE
Support for V11

### ISSUE THREAD

**Issue by ninaran** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#359]
Good morning!

Foundry version 11 has been out for a while now and this module has not been updated yet for it.

Are you currently working on it or is it abandoned?

Thanks!

**Comment by ghost91-** [comment]
I’ve had a brief look and it’s probably not difficult to update. I'll try to find the time to update it soon.

**Comment by ninaran** [comment]
Alright, thanks a ton. I noticed on re-read that the opening post is kinda hostile, sorry for that, didn't mean it like that.

**Comment by ghost91-** [comment]
No worries, I didn’t interpret it like that ;)

**Comment by Nedrapter** [comment]
That's one module I use pretty much on every session. I can't possibly remember all the variables without..This and a Downtime related module are the two I'm waiting for, to update to v11 :)

**Comment by rjbprime** [comment]
Just writing here to get notifications of updates for this. Looking forward to this being updated as and when it can.

**Comment by ninaran** [comment]
> I’ve had a brief look and it’s probably not difficult to update. I'll try to find the time to update it soon.

Hey there, sorry for the additional ping. It's just been three weeks so I'm carefully reaching out again. Is the reason for the delay that the changes are more intense than expected, or just a lack of time?

As someone who doesn't know all that much about variables, references and programming, setting up effects without this module is kinda impossible, is all.

**Comment by ghost91-** [comment]
Sorry for the delay, it was just a lack of time. I have tested it now, and it actually seems to work fine without any change. I have just released a new version (2.9.1) to mark the compatibility with V11. If anything does not work for you, please let me know.
